Customization of the template content closes #3
giis-uniovi/retorch pull request #4
Opened 2023-07-20 09:09 UTC by augustocristian

- Removed modules not used
- Changed module-project names to retorch and retorch-annotations
- Namespace renamed to giis.retorch.annotations
- Test case modifed to pass (uses one of the modules removed)
- Some little spell mistakes corrected.

2023-07-20 12:57 UTC, javiertuya requested changes

2023-07-20 12:57 UTC, javiertuya commented on .idea/.gitignore
Remove the idea configuration files to avoid polluting the repository, and add to .gitignore

2023-07-20 12:57 UTC, javiertuya commented on pom.xml
>  	<url>http://github.com/giis-uniovi/samples-giis-template</url>
Customize url

2023-07-20 12:57 UTC, javiertuya commented on retorch-annotations/pom.xml
>  	<url>http://github.com/giis-uniovi/samples-giis-template</url>
Customize this url

2023-07-20 12:57 UTC, javiertuya commented on sonar-project.properties
>  sonar.projectKey=my:samples-giis-template
key should be my:retorch

However, do we need sonarqube for the annotations?. I think it is no necessary. If you agree, please, remove this file and the corresponding job at `.github/workflows`. If you want SonarQube now, update the key and create an issue to me to configure sonar

2023-07-20 13:16 UTC, javiertuya commented
@augustocristian Just a tip: you don't need to always push every internal commit that you do because each push starts all workflows and sonar (if configured)

2023-07-20 14:28 UTC, augustocristian commented
Dear @javiertuya 
Now everything seems to be working correctly. I made changes to the URL artifacts in the pom.xml. Initially, I thought this information/parametrization was included in the Actions file. However, after reviewing it, I realized it needed to be modified in the pom.xml instead.

2023-07-20 19:24 UTC, javiertuya requested changes
FYI You don't need use mentins to request review. you vsn use the button at the top right of the screen to request review

2023-07-20 19:24 UTC, javiertuya commented on README.md
Customize this description (README.md)

2023-07-21 08:47 UTC, javiertuya requested changes

2023-07-21 08:47 UTC, javiertuya commented on README.md
> +</div>
The readme is a markdown document. Therefore, html should be exclusively used to things that we can't do in markdown. I I'm not wrong all html here can be written using markdown. The most difficult thing could be the TOC, you can see an example at https://github.com/giis-uniovi/qacover

2023-07-21 08:47 UTC, javiertuya commented on README.md
> +@MethodSource("data")
Check indentation, this is literally displayed

2023-07-21 08:47 UTC, javiertuya commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
As before, remove all html, check the whole document

2023-07-21 08:47 UTC, javiertuya commented on README.md
> +This work has been developed under the TestBUS (PID2019-105455GB-C32) and EQUAVEL (PID2022-137646OB-C32) projects supported by [Ministry of Science and Innovation (SPAIN)](https://www.ciencia.gob.es/
Remove equavel at the moment, it is not officially approved

2023-07-21 08:47 UTC, javiertuya commented on README.md
> +The following code snippets illustrates a tes case annotated with several resources and access modes:
spelling: tes case

2023-07-21 08:47 UTC, javiertuya commented on README.md
> +    This repository contains a series of components that compose RETORCH, a E2E test orchestration rchestration framework which aims
spelling: test orchestration rchestration

2023-07-21 08:47 UTC, javiertuya commented on README.md
> +Link: [https://github.com/giis-uniovi/retorch](https://github.com/giis-uniovi/retorch)
redundant, this is this repo

2023-07-21 08:47 UTC, javiertuya commented on README.md
> +```
This reference should be formatted like a paper reference, not as source code

2023-07-21 08:48 UTC, augustocristian commented
Personalized the README, following the sections of td-rules plus some extra (contact  and acks) as well as the the first draft of the annotations

2023-07-21 08:50 UTC, javiertuya commented
@augustocristian Remember that the comment that originated this was *Customize this description: a simple statement to say what is retorch, the annotations. Include a note to explain that annotations are the only available now, but in a near future, other retorch componentes will be available.".

You can keep the details, but please, include the note referred to in the second part

2023-07-21 09:01 UTC, augustocristian commented on README.md
> +</div>
Thanks Javier! Working on it

2023-07-21 09:49 UTC, augustocristian commented on README.md
> +```
@javiertuya , can be interesting study includying this type of files? https://citation-file-format.github.io/

2023-07-21 09:57 UTC, augustocristian commented
> 

I apologize for the misunderstanding. I understood that this minor personalization was intended only in the pom.xml file (with the note that not all components are available at the moment), so when this morning I realized the change resquest in the readme, I thought it was to include all (at least a preliminary version)

2023-07-21 12:43 UTC, javiertuya commented on README.md
> +```
Sounds good, but not for now, we can't delay any longer this PR

2023-07-21 12:46 UTC, augustocristian commented on README.md
> +```
Would you like me to open an issue in this project or the template project with the provided links and information? @javiertuya
Perhaps we can address it in the near to medium future for all projects.

2023-07-21 12:47 UTC, javiertuya commented
@augustocristian Is this for review? there are 2 unresolved conversations. No PR can be merged if any conversation is unresolved.

2023-07-21 12:48 UTC, javiertuya commented on README.md
> +</div>
Still html

2023-07-21 12:48 UTC, javiertuya commented on README.md
> +[(Back to the top)](#contents)
Remove back to the top, this file is small enough to do not need more complications

2023-07-21 12:49 UTC, javiertuya commented on README.md
> +  Software Quality Journal, vol. 28, no. 3, 2020.
journal in italics

2023-07-21 15:27 UTC, javiertuya approved these changes

2023-07-21 15:29 UTC, merged