Orchestration module: Migration of the Resource Identification process code and tests
giis-uniovi/retorch pull request #59
Opened 2024-11-14 15:22 UTC by augustocristian

This PR is related to #58 

- Includes new module with:
    - Most of the model entities
    - Code-functionality of the resource identification
    - Test cases that validate the above functionality
- Necessary  changes in the pipelining code (actions) to make all pass-work

The PR is still failing reporting some circular dependencies related to the logs that doesn't exist, the only dependencies are between  the packages Resource Entity and RetorchUtils (but not viceversa, circular)

2024-11-14 15:30 UTC, augustocristian commented
Good afternoon all!
As suggested by @javiertuya, I've changed the approach to something more incremental:
1. Resource identification
2. Grouping+Scheduling
3. Deployment+Orchtools
Each stage would include the necessary tests, configuration files and other tool stuff. On this PR, I've cleaned and presented the code to make everything as much clean as possible. I've decided to create a new module and not integrate-rename into the annotations due to two important factors (I'think that Javier make this structure for the same reason). 
1. The tool can be used once or several times to generate the necessary scripting-pipelining code, but this code-methods can be removed when everything is generated (and avoid get them from our repository at each test suite execution)
2. The annotations conf-files always remain with the test cases.
The pipeline is reporting problems in sonar,  I've been reviewing the problem and from the best of my knowledge is a false positive (is reporting the loggers as circular reference)

2024-11-15 07:45 UTC, javiertuya requested changes
As a first stage I've reviewed the structure (to allow renamings before reviewing the source code) and general configuration files (poms, workflows, etc.).
After finish the review we can handle the sonar issue that seems to be a false positive.

Remember, DO NOT FORCE PUSH commits that have already been reviewed.

@ClaudiodelaRiva FYI

2024-11-15 07:45 UTC, javiertuya commented on pom.xml
> +        <maven.compiler.target>16</maven.compiler.target>
Why the java version has bumped from 8 to 16? 
-Keep this version to the lowest LTS
-Ensure consistency in versions across all files (poms, workflows, sonarqube, eclipse config)

2024-11-15 07:45 UTC, javiertuya commented on retorch-orchestration/pom.xml
> +	<description>Multimodule maven project template, module without dependencies</description>
- Customize this pom, e.g. title
- Declare depenencies in the parent pom, and inherit in the children
- Dependencies on other modules of this project should be the first ones to reduce the risk of transitive dependencies issues

2024-11-15 07:45 UTC, javiertuya commented on retorch-orchestration/pom.xml
> +			<artifactId>logback-classic</artifactId>
Make a consistent use of logger implementations and configuration: Here, logback is used, but the resource config is log4j2.xml in this module, and logback.xml in the annotations module

2024-11-15 07:45 UTC, javiertuya commented on .github/workflows/build.yml
> +          java-version: '16'
In addition to the comments about java versions:
- Review the worflow name
- Consider change the name from build to test (optional)
- This workflow do not run tests!!
- Generate test report checks
- Publish test report and coverage artifacts
- Ensure that the reports are read by SonarQube

2024-11-15 07:45 UTC, javiertuya commented on retorch-orchestration/src/main/java/giis/retorch/orchestration/model/AccessModeEntity.java
> +public class AccessModeEntity {
We already know that the model contains entities. Remove `Entity` from the model class names

2024-11-15 07:45 UTC, javiertuya commented on retorch-orchestration/src/main/java/giis/retorch/orchestration/resourceidentification/RetorchClassifier.java
> +package giis.retorch.orchestration.resourceidentification;
This package is all about the classifier, however the package name sounds like a different process. Use name `classifier` for the package name

2024-11-15 07:45 UTC, javiertuya commented on retorch-orchestration/src/main/java/giis/retorch/orchestration/resourceidentification/RetorchClassifierUtils.java
> +package giis.retorch.orchestration.resourceidentification;
This does not seems to be a general purpose utility class. It contains all about serialization of resources. A name like `ResourceSerializer` seems to be more appropriate

2024-11-15 07:45 UTC, javiertuya commented on retorch-orchestration/retorchfiles/configurations/retorchCI.properties
> +docker-frontend-name=https://full-teaching-
This configuration seems to be a configuration of the fullteaching system test. Use different names to avoid confusion.

2024-11-15 07:45 UTC, javiertuya commented on retorch-orchestration/retorchfiles/configurations/ClassifierUnitTestsSystemResources.json
> +{
Check if this is tis is used by any test, if not, remove. Same for the .properties file

2024-11-15 07:45 UTC, javiertuya commented on retorch-orchestration/src/test/java/giis/retorch/orchestration/unitary/components/ClassifierTests.java
> +package giis.retorch.orchestration.unitary.components;
Unitary is not a word used to refer unit testing. Also, it makes the namespace larger, and everything is unit test: remove.

The tests are in 6 namespaces, however there are:
- 3 namespaces for the java classes as test data (I assume that it is placed here to compile the classes, it is fine)
- 3 namespaces for 2 test classes and part of the test code moved out to separate classes, this leads to fragmentation, and makes more diffcult to browse over all tests. This kind of fragmentation can be useful if the tests replicate the package structure of the SUT and you need to test non public (but default scoped) methods, but this is not the case here. Everything should be in a single orchestration namespace.

2024-11-15 07:45 UTC, javiertuya commented on retorch-orchestration/pom.xml
> +	<packaging>jar</packaging>
Is far as I understand, this module is who generates a jenkinsfile. As we talked time ago, this could be accomplished by providing this module as a CLI tool. If so, generate an uber jar with the appropriate parameters and (manually) test that everything works with fullteaching and eshopcontainers. Remembar that every build generates the branch snapshots to allow this kind of test without releasing anything to maven central.

This could be posponed, in this case, create an issue for it to handle just after this PR is merged (and place the id here)

2024-11-15 08:52 UTC, augustocristian commented on pom.xml
> +        <maven.compiler.target>16</maven.compiler.target>
The Java version was increased to support toList() method in the streams (Collectors.toList() reports a smell)

2024-11-15 09:03 UTC, javiertuya commented on pom.xml
> +        <maven.compiler.target>16</maven.compiler.target>
A single statement is not a reason to generate a major change in java version to a non LTS.

But, as far as I know streams are implemented since Java 8: https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html

2024-11-15 11:31 UTC, augustocristian commented
@javiertuya  Several doubts:
1. What is the best practice for declaring dependencies in parent-children poms?
1. 1. Declare the dependencies in the parent pom that are going to be used by several modules: JUnit, Loggers, JSON parsers, and declare those dependencies that are only used in certain modules in its pom.
1. 2. Declare everything in the parent pom, and use it as required in the different modules. 
My knowledge about building cycles in Maven is not big, but as far as I am concerned, the first approach would make that we don't "download-use" those dependencies not required to build a certain module
2. The reports that Sonar Cloud must see are only the coverage, no? The test execution record is plotted in the actions.
3. Now the publishing of the snapshots is broken, during the build of the jars is not detecting the annotations library There's some configuration of the javiertuya/branch-snapshots-action@v1.2.3 action that I am missing? I've tried to use the same flag than the  test execution (experienced the same problem in the past) : -am but It didn't work

Thanks a lot for everything!

2024-11-15 15:26 UTC, javiertuya commented
@augustocristian 
> @javiertuya Several doubts:
> 
> 1. What is the best practice for declaring dependencies in parent-children poms?
> 2. 1. Declare the dependencies in the parent pom that are going to be used by several modules: JUnit, Loggers, JSON parsers, and declare those dependencies that are only used in certain modules in its pom.
> 3. 2. Declare everything in the parent pom, and use it as required in the different modules.

See our template https://github.com/giis-uniovi/samples-giis-template for an example:
- all project dependencies declared in the `dependenciesManagement` in the parent pom, This does not import any dependency, it is only declaration
- each module imports (inherits) the dependencies that needs: only group and artifact is needed.
- the exception are other modules in the project that need to specify the version
- for test only dependencies, declare the scope in the parent, it does not need to be declared in the child
- if the child needs a non test dependency to be used in the tests, specify the scope in the child (this will override the default scope)
- see https://maven.apache.org/guides/introduction/introduction-to-the-pom.html for more details on poms and inheritance

>  My knowledge about building cycles in Maven is not big, but as far as I am concerned, the first approach would make that we don't "download-use" those dependencies not required to build a certain module

Parent dependencies  in `dependenciesManagement` are not downloaded, it is only a declaration

> 4. The reports that Sonar Cloud must see are only the coverage, no? The test execution record is plotted in the actions.

Not only, but this is the most important. The tests and status can be also shown under section Meassures->Coverage->Tests (If I remember well, previous versions of SonarQube displayed a summary in the dashboard, now they are more hidden).

> 5. Now the publishing of the snapshots is broken, during the build of the jars is not detecting the annotations library There's some configuration of the javiertuya/branch-snapshots-action@v1.2.3 action that I am missing? I've tried to use the same flag than the  test execution (experienced the same problem in the past) : -am but It didn't work

It is not broken, it is disabled by an `if` condition. Comment-out this condition, I will check it after the merge
> 
> Thanks a lot for everything!

2024-11-15 15:33 UTC, javiertuya commented on retorch-orchestration/pom.xml
> +	<packaging>jar</packaging>
what about this?

2024-11-15 15:42 UTC, javiertuya commented on .github/workflows/build.yml
> +          java-version: '16'
- In this project there is no need of different build and test jobs as full integration and system tests that require some kind of previous deployment are in separate projects. Everything can be made with a single mvn statement.
- I didn't mentioned anything

2024-11-15 15:55 UTC, javiertuya commented on retorch-orchestration/src/test/java/giis/retorch/orchestration/unitary/components/ClassifierTests.java
> +package giis.retorch.orchestration.unitary.components;
- the src/main namespace `giis.retorch.orchestration` is named as  `giis.retorch.orchestration.testdata`
- Move the utils in src/test to `giis.retorch.orchestration` as they are not general purpose utils, they are part of the tests

2024-11-15 16:01 UTC, javiertuya requested changes
I didn't started reviewing the code as there many unresolved comments. Please, read the comments and address them, not less, not more.

2024-11-15 16:11 UTC, javiertuya commented
@augustocristian Do not make changes after you request a review and until I request changes because in the next review I will be unable to focus on the changes since last review. For instance, below there is a commit introduced just before I asked for changes, This implies that these changes are hidden when I want to see only changes since last review.

![image](https://github.com/user-attachments/assets/b2de0377-fea5-4556-86e4-d935b79be15a)

2024-11-15 16:20 UTC, augustocristian commented
Sorry, I've received the notification in the email:
![image](https://github.com/user-attachments/assets/955874ca-e65d-4808-b573-7084afd9fa83)
And I thought that you have finished with the review @javiertuya

2024-11-15 17:11 UTC, javiertuya commented on pom.xml
> +        <maven.compiler.target>16</maven.compiler.target>
@augustocristian @ClaudiodelaRiva Have you read the comments in this thread? It is the second time that I reopen it

2024-11-15 17:16 UTC, javiertuya commented on retorch-orchestration/pom.xml
> +	<packaging>jar</packaging>
Second time, what about this?

2024-11-15 17:18 UTC, javiertuya requested changes
@augustocristian @ClaudiodelaRiva Still unresolved comments (ignored by second time)

2024-11-15 17:55 UTC, augustocristian commented
@javiertuya I don’t want to close the last comment until I’m sure I fully understand what you mean. From the first moment, I completely understood what you wanted: this module will be a Java tool that takes certain parameters (e.g., the package name) and generates the necessary scripting code, without requiring tasks like importing dependencies into the POM or creating a Java class.  
However, I’m still unclear if you want this part to be addressed at the end of the migration, or if we should start the packaging process now (e.g., configuring the appropriate plugin to generate a JAR for this module as an artifact). 
Thanks for everything!

2024-11-15 18:04 UTC, javiertuya commented
@augustocristian It is simple, this is what I wrote:

> This could be posponed, in this case, create an issue for it to handle just after this PR is merged (**and place the id here**)

You created the issue, ok, we can talk later about this in the issue (NOT IN THIS PR). But in this case I requested to place the id in the comment (shown in bold). This is the way to create follow-up issues, create the issue, refer the issue in the comment and close the issue (because the comment directs to where it will be addressed).

2024-11-18 16:27 UTC, javiertuya requested changes
- Java version: It's fine, although you may need to check it later (not now, not in this PR) to ensure the downgraded artifacts to ensure are maintained versions.
- Fat jar: It is not a good practice to answer/discuss on a review comment outside of his comment thread. This is because you can forget the points that were mentioned/discussed, as in this case. This is why I reopened it.

2024-12-03 10:28 UTC, augustocristian commented
@javiertuya I realized today, with Claudio's, that all my comments were unpublished because I unintentionally started a review a couple of weeks ago. I had been waiting for your response, thinking you were busy.
Sorry for all

2024-12-04 08:49 UTC, javiertuya requested changes

2024-12-04 08:49 UTC, javiertuya commented on README.md
> +annotated within the test cases and the Resource information specified in `/retorchfiles/[SUT_NAME]SystemResources.json`.
This is fine as introduction of the module. It describes/mentions the inputs (anotations and resources file), but should be complete to describe the process (what an user must to do) and the outputs (where the pipeline and scripts are placed).

2024-12-04 12:58 UTC, augustocristian commented
@javiertuya  I think we should also update the ACKs of the repository to include EQUAVEL.  But I've got several doubts about use the [ACK of llm-rp](https://github.com/giis-uniovi/retorchx-rp?tab=readme-ov-file#acknowledgments) (It's the official ones, asked-checked with Claudio), or the ["old ones"](https://github.com/giis-uniovi/retorchx-rp?tab=readme-ov-file#acknowledgments)

2024-12-05 07:11 UTC, javiertuya requested changes

2024-12-05 07:11 UTC, javiertuya commented on README.md
> +- Execute the orchestration tool and generate the pipelining-scripting code
Instead of tool, say generator, that gives a better idea of what is doing. Review in all readme and replace by "orchestration generator"

2024-12-05 07:11 UTC, javiertuya commented on README.md
> +into the test suite. The first step is to create several folders to store the configurations and place the `docker-compose.yml`
This section is about the preparation of the test suite, not execution. Remove this first statement

2024-12-05 07:11 UTC, javiertuya commented on README.md
> +[TO-DO] Pending to decide-implement the final version
This is the most important part of the readme, but it is empty. Even if we will have later a cli approach to execute the orchestration generator, it should explain how the jenkinsfile and the other stuff can be generated now. Maybe you need to run a test, a main from the development environment, etc, to allow testing the generation manually.

2024-12-05 10:24 UTC, javiertuya requested changes

2024-12-05 10:24 UTC, javiertuya commented on README.md
> +        toolBox.generateJenkinsfile("giis.sutexample.e2e.functional.tests", "sutexample", "./");
I'm preparing to test this:
- I have retorch (this branch) and retorch-st-fullteaching (main branch) under the same folder
- I create in retorch a main file as indicated here
- I assume that the second parameter can be any string to identify the system, let say sutexample
- I assume that the third paramter is ../../retorch-st-fullteaching (the location of the current jenkinsfile, that I want to regenerate)

But how to set the first parameter? you say that this is the package route (i.e. the package name), but I would need to indicate the folder where I have the test sources that will be processed

2024-12-05 10:29 UTC, augustocristian commented on README.md
> +        toolBox.generateJenkinsfile("giis.sutexample.e2e.functional.tests", "sutexample", "./");
Two important remarks: 
The second parameter [SUTNAME] must correspond with the [SUTNAME]Systemresources.json
The third parameter must be the complete package route to the tests, in Fullteaching: com.fullteaching.e2e.no_elastest.functional.test.
Let me update the README.md with the first indication, how I can explain correctly the second one? @javiertuya

2024-12-05 10:34 UTC, javiertuya commented on README.md
> +        toolBox.generateJenkinsfile("giis.sutexample.e2e.functional.tests", "sutexample", "./");
Check it carefully, because from this comment I have more questions: If the third parameter is the location of the tests (note that you are specifying a namespace, not a folder location), where I can specify the location of the jenkinsfile? And then, what is the first parameter?

2024-12-05 10:36 UTC, augustocristian commented on README.md
> +        toolBox.generateJenkinsfile("giis.sutexample.e2e.functional.tests", "sutexample", "./");
I hope that this clarifies everythong: 

```markdown
Once all the files created and the `docker-compose.yml` is prepared, to execute the generator we only need to create a 
main class and instantiate an `OrchestratinGenericToolbox` object. Calling the `generateJenkinsFile()` method with the following 
parameters:
- `packageRoute`: String that specifies the complete package name to the test folders,
- `systemName`: String that specifies the system name, must correspond with the name used in the [Resources JSON file](#create-the-resourcejson-file)
- `jenkinsFilePath`: String with the destination of the `Jenkinsfile`.
```

2024-12-05 10:50 UTC, augustocristian commented
@javiertuya, maybe would be a good idea start removing from the old repository all that is migrated and made a "highly coupled" system importing this orchestration module in GitLab, testing that everything that we change not "breaks" the rest of the implementation?

2024-12-05 10:51 UTC, javiertuya commented on README.md
> +        toolBox.generateJenkinsfile("giis.sutexample.e2e.functional.tests", "sutexample", "./");
@augustocristian I still does not understant how the folders that have the tests can be located with only the package name: if the sut is a single project, assuming a maven structure, it will be under src/test/java, but if it is multimodule, it would be module/src/test/java...

2024-12-05 10:59 UTC, augustocristian commented on README.md
> +        toolBox.generateJenkinsfile("giis.sutexample.e2e.functional.tests", "sutexample", "./");
I think that we never considered the case of one multimodule project, the tool for now only supports projects with a single module. I don't know if specifying the module at the start of the package (e.g.modulename.com.fullteaching.e2e.no_elastest.functional.test).
Currently, we change the package name by the directory, this is how we are retrieving the classes:

``` java
   private static File getPackageSourceDirectory(String packageName) throws EmptyInputException, URISyntaxException {
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        if (classLoader == null) {
            throw new IllegalStateException("ClassLoader could not be Loaded");
        }
        URL resourceURL = classLoader.getResource(packageName.replace('.', '/'));
        if (resourceURL == null) {
            throw new EmptyInputException("Package " + packageName + " not found on classpath.");
        }
        URI uri = resourceURL.toURI();
        Path path = Paths.get(uri);
        return path.toFile();
    }
```
I'll will check later how to change this implementation to something that supports multimodule
Thanks for all! @javiertuya

2024-12-05 12:46 UTC, javiertuya commented on README.md
> +        toolBox.generateJenkinsfile("giis.sutexample.e2e.functional.tests", "sutexample", "./");
@augustocristian If it is a constraint to no multimodule projects is fine for now, just say this in the readme/instructions

2024-12-11 10:41 UTC, augustocristian commented
I've added it in the README.md the requirement of a single module project. There's something more that I am missing @javiertuya

2024-12-12 09:09 UTC, javiertuya requested changes
I still can't execute the jenkinsfile generation

2024-12-12 09:09 UTC, javiertuya commented on README.md
Check section *Preparing the docker-compose.yml file*. This is a diff file, that does not allow to copy and paste to customize in order to test the generation. If you are referring to some files in other reports, just provide links.

2024-12-12 09:09 UTC, javiertuya commented on README.md
>  import retorch.orchestration.main.OrchestrationGenericToolBox;
This namespace does not exist. Did you tested the instructions that are provided in the readme?

2024-12-12 09:20 UTC, augustocristian commented on README.md
>  import retorch.orchestration.main.OrchestrationGenericToolBox;
Some functionality corresponds to the orchestration generation toolbox and has  not yet migrated to the repository. That's why I left the section empty with a TO-DO in the first commits. 
Without regarding it, in the next commit I'll update the package to fit the actual package structure (giis.retorch.orchestration.main.OrchestrationGenericToolBox;)

2024-12-12 09:24 UTC, augustocristian commented on README.md
Yes, this diff was placed in the README.md intentionally. My idea was showcase how a "standard" docker-compose.yml, must be adapted for the tool. As you recommended, maybe its a good idea showcase the  docker-compose in the original Fullteaching repository and a comparison with our docker compose? Also for eshopcontainers?

2024-12-12 09:26 UTC, augustocristian commented on README.md
>  import retorch.orchestration.main.OrchestrationGenericToolBox;
I am not able to test the instructions yet because this part corresponds to code that has not already been migrated* @javiertuya

2024-12-12 09:40 UTC, augustocristian commented on README.md
I 've removed the diff and added the references, its better now?

2024-12-12 09:51 UTC, javiertuya commented on README.md
>  import retorch.orchestration.main.OrchestrationGenericToolBox;
@augustocristian But the scope of this module, wasn't it to generate the jenkinsfile? 
See when I commented this: https://github.com/giis-uniovi/retorch/pull/59#discussion_r1871100530.

Therefore, the documentation is essentially wong, it describes orchestration in general, but this requires two modules (this and the next one to be migrated).

Mark the latest comments as resolved and request the lastest review. I will merge this module as is now.

2024-12-12 09:57 UTC, javiertuya approved these changes
Go ahead with the next module. This should be the module that generates the jenkinsfile

2024-12-12 09:58 UTC, merged