Migration of the scheduler and orchestrator packages
giis-uniovi/retorch pull request #65
Opened 2024-12-13 18:03 UTC by augustocristian

This PR  is related and closes #58 contains the following changes:
- The scheduler and orchestrator packages, with the necessary code to generate the TJobs and Execution plans
- The necessary objects in the model folder
- The unitary test cases of both components
- The integration test of the whole orchestration generator.

2024-12-13 20:27 UTC, augustocristian commented
As you requested @javiertuya   https://github.com/giis-uniovi/retorch/pull/59#pullrequestreview-2498707364, I've migrated the module that generates the Jenkinsfiles (nothing related to the UsageProfile or the Cost estimation). 
I've refactored a lot and the current version is far away to the ones that are in GitLab, I've removed a lot of duplications and dummy methods not used.

2024-12-15 17:32 UTC, javiertuya requested changes

2024-12-15 17:32 UTC, javiertuya commented on retorch-orchestration/src/main/java/giis/retorch/orchestration/model/ExecutionPlan.java
> +
Why constant values are? If there is a clear criterion for susing letters to identify tjobs, should there be a method that provides a new identifier when needed? And putting this in an enum seems a bit weird. In the end you will be building an array of identifiers.

2024-12-15 17:32 UTC, javiertuya commented on retorch-orchestration/src/main/java/giis/retorch/orchestration/orchestrator/RetorchOrchestrator.java
> +public interface RetorchOrchestrator {
This is a java interface, the most used convention is to start with uppercase I.

2024-12-15 17:32 UTC, javiertuya commented on retorch-orchestration/src/main/java/giis/retorch/orchestration/orchestrator/RetorchOrchestrator.java
> + * The {@code RetorchOrchestrator}  is the interface which implement the different Orchestrators used to generate
An interface does not implements nothing (unless it contains default implementations, which is not the case here).

2024-12-15 17:32 UTC, javiertuya commented on pom.xml
> +            <dependency><!-- This package allows make intersections and complementary operations between lists https://mvnrepository.com/artifact/org.apache.commons/commons-collections4 -->
IMO this and the commons-io comments should be removed

2025-01-01 17:41 UTC, augustocristian commented on README.md
>  ### Executing the Orchestration generator
I was experiencing some problems with the IDE during the past week, I've managed more or less to solve it (working with the LAPTOP and DESKTOP in parallel). Some remarks (that I don't understand):
1. FullTeaching was with the old orchestration generation tool, that's why I don't find anything. Now the  [ft_AlignOrchGeneratorVersion](https://github.com/giis-uniovi/retorch-st-fullteaching/tree/ft_AlignOrchGeneratorVersion) is fully updated and working. 
2. I've created a class with a simple call to the main in the FullTeaching project, importing the snapshot orchestration library, by means adding the dependency:
```yaml

```

2025-01-24 18:31 UTC, javiertuya requested changes

2025-01-24 18:31 UTC, javiertuya commented on README.md
> +annotated within the test cases and the Resource information specified in `/retorchfiles/configurations/[SUT_NAME]SystemResources.json`.
Why an absolute path? Everything should be relative to somewhere (e.g. the root of the SUT project)

2025-01-24 18:31 UTC, javiertuya commented on README.md
> +main class `giis.retorch.orchestration.OrchestrationIntegrationTests.javaOrchestationGeneratorMainClass` with the following 3 parameters as arguments:
In the latest reviewd version, the main class was something under src/main, whith is the right way.
However, no the main class is under the test folder, and it does not exist.
- Please, carefully TEST the generation process against the documentation (manual test)
- Don' forget resolve conversations (there is an unresolved one from the previous review)

2025-01-30 18:47 UTC, javiertuya requested changes

2025-01-30 18:47 UTC, javiertuya commented on README.md
> +main class ` giis.retorch.orchestration.main.OrchestationGeneratorMainClass` into the test `/test` package with the following 3 parameters as arguments:
This class is not in the test package

2025-01-30 18:47 UTC, javiertuya commented on README.md
> +```
Remove this snippet because:
- it is a copy of the main class of the retorch generator, but ignores the arguments and sets arguments inside the method. 
- It is not the way of executing the retorch generator. Remember that the generator must produce the jenkinsfile and the associated stuff when execucted **from retorch**, not from the SUT (if executed from the SUT, this should be modified to include all retorch dependencies, but only the annotations are needed).

Just indicate what are the three arguments that the tester should pass to the main class of the retorch generator to create the jenkinsfile of a project (fullteaching is good as example), provided that both retorch and fullteaching are in sibling folders.

And remember test it manually against the documentation in this readme.

2025-01-31 11:02 UTC, augustocristian commented on README.md
> +```
Hi @javiertuya, I've been reviewing the entire process and have a few questions:
The current tool retrieves annotations from the Java classes by accessing the class loader, which I believe has always been the case. However, when using the jar as a tool (e.g., executing it from another project or from the main package in the SUT), it can't access the test annotations because, by default, the test classes are not generated and thus cannot be accessed—at least to the best of my knowledge. I included the `\test` package in the README.md, but I've come to realize that this needs clarification: the main method should be in the same package as the annotated test cases in the SUT to access the annotations.
I will go ahead and update the README.md, and I suggest that this issue be addressed in a separate PR.

2025-02-03 17:19 UTC, javiertuya commented on README.md
> +```
@augustocristian The  last justification for not being able to generate the jenkinsfile from retorch was that that it was not able to locate some files (see at the end of https://github.com/giis-uniovi/retorch/pull/65#discussion_r1900437145). But with the above info, the problem is very different, maybe requiring non trivial changes.

Therefore, proceed with the generation of the jenkinsfiles from the SUT:
- Remove the main class in retorch, because it is not needed anymore
- Run retorch from the tests in the SUT, provide a template in the documentation (not a main class, but a test class) and the appropriate instructions (configure dependencies, set an ignore annotation to this class when pushing the SUT...)

2025-02-06 19:28 UTC, javiertuya requested changes

2025-02-06 19:28 UTC, javiertuya commented on README.md
> +@Disabled("Exclude to execute this class when pushing the SUT")
Running this scenario, from the fullteaching project:

1) Customize the test:
```
package com.fullteaching.e2e.no_elastest.functional.test;

import giis.retorch.orchestration.classifier.EmptyInputException;
import giis.retorch.orchestration.generator.OrchestrationGenerator;
import giis.retorch.orchestration.orchestrator.NoFinalActivitiesException;
import giis.retorch.orchestration.scheduler.NoTGroupsInTheSchedulerException;
import giis.retorch.orchestration.scheduler.NotValidSystemException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.URISyntaxException;

//@Disabled("Exclude to execute this class when pushing the SUT")
class RetorchGenerateJenkinfileTest {
  @Test
  void testGenerateJenkinsfile() throws NoFinalActivitiesException, NoTGroupsInTheSchedulerException, EmptyInputException, IOException, URISyntaxException, NotValidSystemException, ClassNotFoundException {
    OrchestrationGenerator orch= new OrchestrationGenerator();
    orch.generateJenkinsfile("com.fullteaching.e2e.no_elastest", "FullTeaching", "./"); // TO-DO adjust the rootPackageNameTests,systemName and jenkinsFilePath parameters 
  }
}
```

**FAILURE 1**: Does not compile because of the orchestrator missing dependency. The documentation does not mention that this dependency is required.

2) Configure the fullteaching pom to use the branch snapshot dependency, version  1.1.1-ft_migrateschedulerorchestrator-SNAPSHOT. Compiles fine (from eclipse)

3) Run the test (RetorchGenerateJenkinfileTest). Exception raised:
```
java.nio.file.NoSuchFileException: retorchfiles\configurations\FullTeachingSystemResources.json
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
...
```

**Failure 2**: The location of FullTeachingSystemResources.json does not match with the specified in the documentation

4) Copy the above file from resources to configurations.

5) Run the test (from eclipse). Exception raised:

```
java.lang.UnsupportedClassVersionError: org/openqa/selenium/TimeoutException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at giis.retorch.orchestration.classifier.RetorchClassifier.findClasses(RetorchClassifier.java:83)
	at giis.retorch.orchestration.classifier.RetorchClassifier.findClasses(RetorchClassifier.java:81)
	at giis.retorch.orchestration.classifier.RetorchClassifier.getSystemFromPackage(RetorchClassifier.java:114)
	at giis.retorch.orchestration.generator.OrchestrationGenerator.getJenkinsOrchestrator(OrchestrationGenerator.java:82)
	at giis.retorch.orchestration.generator.OrchestrationGenerator.generateJenkinsfile(OrchestrationGenerator.java:40)
	at com.fullteaching.e2e.no_elastest.functional.test.RetorchGenerateJenkinfileTest.testGenerateJenkinsfile(RetorchGenerateJenkinfileTest.java:19)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.ArrayList.forEach(ArrayList.java:1249)

```

**Failure 3**: There is a java version mismatch. Fullteaching requires java 8, from eclipse, the project is correctly configured with this version, but there is some component in java 11 (Selenium).

6) Run the test from maven, `mvn test -Dtest=RetorchGenerateJenkinfileTest`, test result:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.fullteaching.e2e.no_elastest.functional.test.RetorchGenerateJenkinfileTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.056 s <<< FAILURE! -- in com.fullteaching.e2e.no_elastest.functional.test.RetorchGenerateJenkinfileTest
[ERROR] com.fullteaching.e2e.no_elastest.functional.test.RetorchGenerateJenkinfileTest.testGenerateJenkinsfile -- Time elapsed: 1.020 s <<< ERROR!
giis.retorch.orchestration.classifier.EmptyInputException: No annotated methods found in class com.fullteaching.e2e.no_elastest.common.ChromeUser
        at giis.retorch.orchestration.classifier.RetorchClassifier.getSystemFromClass(RetorchClassifier.java:157)
        at giis.retorch.orchestration.classifier.RetorchClassifier.getSystemFromPackage(RetorchClassifier.java:116)
        at giis.retorch.orchestration.generator.OrchestrationGenerator.getJenkinsOrchestrator(OrchestrationGenerator.java:82)
        at giis.retorch.orchestration.generator.OrchestrationGenerator.generateJenkinsfile(OrchestrationGenerator.java:40)
        at com.fullteaching.e2e.no_elastest.functional.test.RetorchGenerateJenkinfileTest.testGenerateJenkinsfile(RetorchGenerateJenkinfileTest.java:19)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   RetorchGenerateJenkinfileTest.testGenerateJenkinsfile:19 » EmptyInput No annotated methods found in class com.fullteaching.e2e.no_elastest.common.ChromeUser
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Failure 4**: It seem that already annotated methods are expected, but this method is who should annotate the methods. 

7) Check against the whole documentation: keep only the configuration files indicated by the documentation, remove the others. and run the orchestration generator. **BLOCKED**

2025-02-07 08:16 UTC, javiertuya commented on README.md
> +@Disabled("Exclude to execute this class when pushing the SUT")
@augustocristian Forget (for the moment) the comments in this last review. This PR is extremely large and is unmanageable, checking changes from last commit takes to long to show.

I decided merge this PR and handle the generator execution problems in an issue.

2025-02-07 08:16 UTC, merged

2025-02-07 08:38 UTC, javiertuya commented on README.md
> +@Disabled("Exclude to execute this class when pushing the SUT")
Closing this conversation, follow up made in a separate issue: #75